# Key: Value
# key: dan sonra değeri bitişik yazmak hatadır
# alt kırılım şeklindeki özellik aynı hizada yazılırsa htadır
server:
  port: 9090

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;databaseName=JoinTestDB;integratedSecurity=true;trustServerCertificate=true
  jpa:
    hibernate:
      ddl-auto: update  #create-drop, create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect